import 'package:dharma_ai/models/verse.dart';

class MockScriptureData {
  static const List<Verse> gitaVerses = [
    Verse(
      id: 'BG_2_47',
      bookName: 'Bhagavad Gita',
      chapter: 2,
      verseNumber: 47,
      sanskritText: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥',
      englishTransliteration: 'karmaṇy-evādhikāras te mā phaleṣu kadācana\nmā karma-phala-hetur bhūr mā te saṅgo ’stv akarmaṇi',
      translation: 'You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions. Never consider yourself to be the cause of the results of your activities, nor be attached to inactive status.',
      commentary: 'This famous verse outlines the philosophy of Karma Yoga—selfless service. Sri Krishna teaches Arjuna that holding onto expectations of reward brings anxiety, disappointment, and binding attachment. True freedom lies in performing actions as an offering to the Divine, without self-seeking motives. By centering our focus on the process rather than the outcome, we enter a state of peaceful flow and spiritual elevation.',
      wordMeanings: {
        'karmani': 'in the performance of prescribed duties',
        'eva': 'only',
        'adhikarah': 'right',
        'te': 'your',
        'ma': 'never',
        'phalesu': 'in the fruits of actions',
        'kadacana': 'at any time',
        'karma-phala': 'the results of actions',
        'hetuh': 'cause',
        'bhuh': 'consider yourself',
        'sangah': 'attachment',
        'astu': 'let there be',
        'akarmani': 'in inaction'
      },
    ),
    Verse(
      id: 'BG_2_20',
      bookName: 'Bhagavad Gita',
      chapter: 2,
      verseNumber: 20,
      sanskritText: 'न जायते म्रियते वा कदाचिन्\nनायं भूत्वा भविता वा न भूयः।\nअजो नित्यः शाश्वतोऽयं पुराणो\nन हन्यते हन्यमाने शरीरे॥',
      englishTransliteration: 'na jāyate mriyate vā kadācin\nnāyaṁ bhūtvā bhavitā vā na bhūyaḥ\najo nityaḥ śāśvato ’yaṁ purāṇo\nna hanyate hanyamāne śarīre',
      translation: 'For the soul there is neither birth nor death at any time. He has not come into being, does not come into being, and will not come into being. He is unborn, eternal, ever-existing and primeval. He is not slain when the body is slain.',
      commentary: 'Sri Krishna describes the eternal, indestructible nature of the soul (Atman) to alleviate Arjuna’s grief over bodily death. The body goes through birth, growth, change, decay, and death, but the consciousness inside remains unaffected. Realizing this core truth establishes us in deep equanimity, allowing us to face life’s changes without fear.',
      wordMeanings: {
        'na': 'never',
        'jayate': 'takes birth',
        'mriyate': 'dies',
        'va': 'or',
        'kadacit': 'at any time',
        'ayam': 'this soul',
        'bhutva': 'having come into being',
        'bhavita': 'will come into being',
        'ajah': 'unborn',
        'nityah': 'eternal',
        'sasvatah': 'ever-existing',
        'puranah': 'primeval',
        'hanyate': 'is slain',
        'sarire': 'the body'
      },
    ),
    Verse(
      id: 'BG_9_22',
      bookName: 'Bhagavad Gita',
      chapter: 9,
      verseNumber: 22,
      sanskritText: 'अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते।\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्॥',
      englishTransliteration: 'ananyāś cintayanto māṁ ye janāḥ paryupāsate\nteṣāṁ nityābhiyuktānāṁ yoga-kṣemaṁ vahāmy aham',
      translation: 'But those who always worship Me with exclusive devotion, meditating on My transcendental form—to them I carry what they lack, and I preserve what they have.',
      commentary: 'This verse represents a divine promise of absolute protection and grace. For a seeker who is single-mindedly aligned with their higher consciousness (Krishna), the universe provides all material and spiritual necessities (yoga) and guards their existing progress (kshema). It releases the seeker from the burden of anxious struggle, cultivating deep trust.',
      wordMeanings: {
        'ananyah': 'having no other object of devotion',
        'cintayantah': 'meditating on',
        'mam': 'Me',
        'ye': 'who',
        'janah': 'persons',
        'paryupasate': 'worship',
        'tesam': 'of them',
        'nitya': 'always',
        'abhiyuktanam': 'absorbed in devotion',
        'yoga': 'what they lack / spiritual union',
        'ksemam': 'what they have / preservation',
        'vahami': 'carry',
        'aham': 'I'
      },
    ),
    Verse(
      id: 'BG_18_66',
      bookName: 'Bhagavad Gita',
      chapter: 18,
      verseNumber: 66,
      sanskritText: 'सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज।\nअहं त्वां सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः॥',
      englishTransliteration: 'sarva-dharmān parityajya mām ekaṁ śaraṇaṁ vraja\naham tvāṁ sarva-pāpebhyo mokṣayiṣyāmi mā śucaḥ',
      translation: 'Abandon all varieties of religion and surrender unto Me alone. I shall deliver you from all sinful reactions. Do not fear.',
      commentary: 'Often considered the final essence of the Bhagavad Gita (the Charama Shloka). Krishna asks Arjuna to let go of external rites, duties, and intellectual calculations of right/wrong, and simply seek refuge in the Supreme Consciousness. Surrender is not defeat; it is the ultimate act of alignment, which instantly dissolves karmic baggage and replaces fear with divine assurance.',
      wordMeanings: {
        'sarva-dharman': 'all varieties of duties/paths',
        'parityajya': 'abandoning',
        'mam': 'unto Me',
        'ekam': 'only',
        'saranam': 'refuge',
        'vraja': 'go / surrender',
        'tvam': 'you',
        'sarva-papebhyah': 'from all reactions to sin',
        'moksayisyami': 'will deliver',
        'ma': 'do not',
        'sucah': 'worry/grieve'
      },
    ),
  ];
}
